spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/youcafeteria
    username: youcafeteria
    password: youcafeteria
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: db/changelog/master.yaml
    enabled: true
